- type: job
  id: NachalnikVdnh
  name: Начальник ВДНХ
  description: Вы обладаете всей полнотой власти на этой станции.
  playTimeTracker: NachalnikVdnh
  startingGear: M14DefaultZBTGear
  icon: "JobIconvdnh"
  canBeAntag: true

- type: entity
  id: M14SpawnPointNachalnikVdnh
  parent: SpawnPointJobBase
  name: SpawnNachalnikVdnh
  components:
  - type: SpawnPoint
    job_id: NachalnikVdnh
  - type: Sprite
    layers:
      - state: green
      - state: cargo_tech
      - sprite: Markers/jobs.rsi


- type: playTimeTracker
  id: NachalnikVdnh