- type: job
  id: Stalker
  name: Сталкер
  description: Ищите следы старой цивилизации по техничкам,нанимайтесь,провозите контрабанду,собирайте оружие у техников.
  playTimeTracker: Stalker
  startingGear: M14DefaultZBTGear
  icon: "JobIconvdnh"
  canBeAntag: true

- type: entity
  id: M14SpawnPointStalker
  parent: SpawnPointJobBase
  name: SpawnStalker
  components:
  - type: SpawnPoint
    job_id: Stalker
  - type: Sprite
    layers:
      - state: green
      - state: cargo_tech
      - sprite: Markers/jobs.rsi


- type: playTimeTracker
  id: Stalker