- type: job
  id: M14Gensek
  name: Генсек
  description: Вы великий вождь вашей станции,людей ну и носитель коммунистической революции во всем метро.
  playTimeTracker: M14Gensek
  startingGear: M14DefaultZBTGear
  icon: "JobIconKL"
  canBeAntag: true

- type: playTimeTracker
  id: M14Gensek

- type: startingGear
  id: M14DefaultZBTGear
  equipment:
    head: ClothingHeadHatUshanka
    jumpsuit: ClothingUniformJumpsuitColorGrey
    pocket1: SurvivalKnife
    id: M14Tablet