- type: job
  id: M14SecurityVDNKH
  name: Охранник ВДНХ
  description: Вы обладаете всей полнотой власти на этой станции.
  playTimeTracker: M14SecurityVDNKH
  startingGear: M14SecurityVDNKHGear
  icon: "JobIconVDNKH"
  canBeAntag: true

- type: startingGear
  id: M14SecurityVDNKHGear
  equipment:
    head: ClothingHeadHelmetScrap
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsWork
    back: ClothingBackpack
    pocket1: SurvivalKnife