- type: job
  id: M14StalkerVDNKH
  name: Сталкер
  description: Ищите следы старой цивилизации по техничкам,нанимайтесь,провозите контрабанду,собирайте оружие у техников.
  playTimeTracker: M14StalkerVDNKH
  startingGear: M14StalkerVDNKHGear
  icon: "JobIconVDNKH"
  canBeAntag: true

- type: startingGear
  id: M14StalkerVDNKHGear
  equipment:
    head: M14ClothingHeadHatUshankaBrown
    jumpsuit: M14ClothingUniformTelogreykaBrown
    id: M14Tablet
    shoes: M14ClothingShoesValenki
    gloves: ClothingHandsGlovesHop
    back: ClothingBackpack