[game]
hostname = "🚇 Metro14 - ЗБТ ☣️"
desc = "Первый русскоязычный сервер по вселенной Metro 2033 с повышенным уровнем РП и доступом по вайтлисту.\nДля получения доступа обратитесь в наш Discord!"
maxplayers = 100
soft_max_players = 80
map_rotation = true
role_timers = true

[server]
lobby_name = "️🚇 Metro14 - ЗБТ ☣️"

[rules]
time = 10.0

[whitelist]
enabled = true

[hub]
advertise = false
tags = "lang:ru,rp:high,region:eu_e"
