####################

- type: startingGear
  id: HeadOfRedLineGear
  equipment:
    neck: M14ClothingNeckMantleRedLine
    mask: ClothingMaskNeckGaiterRed
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpack