- type: job
  id: M14Medicsparta
  name: Медик спарты
  description: Вы медик спарты. Помогайте своим товарищам и окружающим.
  playTimeTracker: M14Medicsparta
  startingGear: M14DefaultZBTGear
  icon: "JobIconSparta"
  canBeAntag: true

- type: playTimeTracker
  id: M14Medicsparta

- type: entity
  id: M14SpawnPointM14Medicsparta
  parent: SpawnPointJobBase
  name: SpawnPointM14Medicsparta
  components:
  - type: SpawnPoint
    job_id: M14Medicsparta
  - type: Sprite
    layers:
      - state: green
      - state: cargo_tech
      - sprite: Markers/jobs.rsi