- type: job
  id: M14Polkovnik
  name: Полковник Спарты
  description: Вы лидер спарты. Храните клятву,защищайте метро
  playTimeTracker: M14Polkovnik
  startingGear: M14DefaultZBTGear
  icon: "JobIconSparta"
  canBeAntag: true

- type: jobIcon
  parent: JobIcon
  id: JobIconSparta
  icon:
    sprite: _Metro14/Interface/job_icons.rsi
    state: sparta
  jobName: sparta

- type: playTimeTracker
  id: M14Polkovnik

- type: entity
  id: SpawnPointM14Polkovnik
  parent: SpawnPointJobBase
  name: SpawnPointM14Polkovnik
  components:
  - type: SpawnPoint
    job_id: M14Polkovnik
  - type: Sprite
    layers:
      - state: green
      - state: cargo_tech
      - sprite: Markers/jobs.rsi