- type: jobIcon
  parent: JobIcon
  id: JobIcontechs
  icon:
    sprite: _Metro14/Interface/job_icons.rsi
    state: techs
  jobName: techs


- type: department
  id: M14Texniki
  name: M14Texniki-name
  description: department-Science-description
  color: "#dfc800"
  roles:
  - NachalnikTexniki
  - Texniki