- type: job
  id: NachalnikTexniki
  name: Начальник Техников
  description: Вы обладаете всей полнотой власти на этой станции.
  playTimeTracker: NachalnikTexniki
  startingGear: M14DefaultZBTGear
  icon: "JobIcontechs"
  canBeAntag: true

- type: entity
  id: M14SpawnPointNachalnikTexniki
  parent: SpawnPointJobBase
  name: SpawnNachalnikTexniki
  components:
  - type: SpawnPoint
    job_id: NachalnikTexniki
  - type: Sprite
    layers:
      - state: green
      - state: cargo_tech
      - sprite: Markers/jobs.rsi


- type: playTimeTracker
  id: NachalnikTexniki