- type: job
  id: M14Furer
  name: Фюрер
  description: Вы великий вождь.
  playTimeTracker: M14Furer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 6h
  startingGear: SecurityOfficerGear
  icon: "JobIconGydra"
  canBeAntag: true

- type: jobIcon
  parent: JobIcon
  id: JobIconGydra
  icon:
    sprite: _Metro14/Interface/job_icons.rsi
    state: gydra
  jobName: gydravci

- type: playTimeTracker
  id: M14Furer

- type: entity
  id: M14SpawnPointGydraFurer
  parent: SpawnPointJobBase
  name: SpawnPointGydraFurer
  components:
  - type: SpawnPoint
    job_id: M14Furer
  - type: Sprite
    layers:
      - state: green
      - state: cargo_tech
      - sprite: Markers/jobs.rsi