- type: job
  id: M14SoldierGydra
  name: Солдат Гидры
  description: Вы великий представитель гидры. Цвет метро.
  playTimeTracker: M14SoldierGydra
  startingGear: M14DefaultZBTGear
  icon: "JobIconGydra"
  canBeAntag: true

- type: playTimeTracker
  id: M14SoldierGydra


- type: entity
  id: M14SpawnPointM14SoldierGydra
  parent: SpawnPointJobBase
  name: SpawnPointM14SoldierGydra
  components:
  - type: SpawnPoint
    job_id: M14SoldierGydra
  - type: Sprite
    layers:
      - state: green
      - state: cargo_tech
      - sprite: Markers/jobs.rsi